FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm i

# Copy application code
COPY node-job.js .

RUN chmod +x node-job.js

CMD ["node", "node-job.js"]

